CREATE TABLE university.students
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    student_name          VARCHAR(255),
    student_surname       VARCHAR(255),
    group_name       VARCHAR(255),
    admitted_year INTEGER                                 NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (id)
);