CREATE TABLE university.universites
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_universites PRIMARY KEY (id)
);

insert into university.universites(id, name) values (898989, 'IITU'), (4899889, 'KBTU'), (1551656, 'SDU');

create table university.users
(
    id            bigint generated by default as identity not null,
    name          varchar(255),
    surname       varchar(255),
    age           integer                                 not null,
    university_id bigint,
    constraint pk_users primary key (id)
);

alter table university.users
    add constraint fk_users_on_university foreign key (university_id) references university.universites (id);



